### ISSUE TITLE
Typo in model.py

### ISSUE THREAD

**Issue by felofsson** [matumaros/pypedrive#10]
Line 12 in model.py should be `'Deals': 'deals'` previously ` 'Deal': 'deals'`. 

There will be an error in __init__ otherwise, when `self.__path = self.MAPPING[name]` is called (and there is no corresponding key named "Deals").

**Comment by matumaros** [comment]
Thank you, this was not a mistake in the code. I forgot to update the readme. All objects are in singular form.
